### ISSUE TITLE
missing default values for input parameters of `normalizer.lemmatize_text()`

### ISSUE THREAD

**Issue by mromanello** [questoph/spellux#2]
Calling the function as described in the documentation

```python
spellux.lemmatize_text(tokens, sim_ratio=0.8)
```

fails as the `output` and `lemdict` parameters are missing. This could be avoided by having a default for `output` (e.g. `json`) and defaulting `lemdict` to the global variable with same name defined in the `normalize` module. Or just update the documentation with a working example ;-)

https://github.com/questoph/spellux/blob/725547b4c44d7bf8008e89be41cd13354e11d3b9/spellux/normalizer.py#L320-L356

**Comment by questoph** [comment]
hi there. you're right for the lemdict parameter, forgot to set this in def statement. the output, though, is used nowhere in the function. therefore i'm wondering what might cause the problem here.
i'll fix the parameter in the function.

**Comment by questoph** [comment]
should be fixed now. added the lemdict as default parameter.
